import 'package:flutter_test/flutter_test.dart';

/// The runtime claims this story makes and does **not** observe.
///
/// AGENTS.md §8: a claim that is not observed in this container is stated as
/// unobserved. This test names the ones the panel adapter is owed, so they are
/// owed rather than forgotten. It has no body on purpose — it must never be
/// written in a way that could pass here.
void main() {
  test(
    'CAP-1/CAP-14: the panel becomes visible and focused, hides when it loses '
    'focus, and survives a real double press (AD-8)',
    () {
      fail('this test has no body — see the skip reason');
    },
    skip:
        'not fully observable in this container, and two of the claims this '
        'row used to make about itself have now been observed. CAP-1 asks '
        'for a panel that is visible AND focused and CAP-14 for a hide when '
        'it loses focus; what is missing here for everything else below is a '
        'real desktop session — no compositor, no xdg-desktop-portal, no '
        'session bus and no login. Correcting what this reason used to say, '
        'and it was wrong in a way that cost something. It asserted there was '
        '"no reachable X display", and argued that standing one up closed '
        'nothing because "a bare X server has no compositor", so there would '
        'be nothing on a synthetic display to observe visible AND focused or '
        'a hide on focus loss against. Both halves are false, and were '
        'measured false here between 2026-09-04 and 2026-09-10: Xvfb :99 plus '
        'openbox 3.6.1 — a real window manager, not a bare server — plus the '
        'built release bundle produced a real X11 grab, a real mapped and '
        'focused panel, and a real focus-loss hide classified four separate '
        'ways. The first thing that run found was a major CAP-14 defect '
        '(G-01-13) that this row, while asserting its own blindness, had not. '
        'The run is written up in test/platform/panel-toggle-observation.md, '
        'the defect and its fix are DW-122, and the refuted premise — shared '
        'with DW-9, DW-26 and DW-44 — is DW-123. keybinder-3.0 is installed '
        'too: `pkg-config --modversion keybinder-3.0` answers 0.3.2 here, as '
        'story 7 established. What those two claims are still owed is a real '
        'desktop rather than a display: every verdict in that record came '
        'from one window manager on a synthetic server, with every press sent '
        'by xdotool (XTEST) rather than by a finger, so GNOME/Mutter and '
        'KDE/KWin are unmeasured and DW-9 stays open for them. '
        'It also owes the one assumption the _outstanding guard rests on and '
        'no test here can check: that a request\'s own window echo arrives '
        'while that request is still in flight, rather than after its '
        'method-channel reply. The plugin source says it does — _emit_event '
        'is called synchronously from on_window_show/on_window_hide '
        '(window_manager-0.5.2/linux/window_manager_plugin.cc:959, :987, '
        ':993), which fire inside the gtk_widget_show the method handler '
        'itself calls, so the event goes out on the channel before that '
        'handler returns its reply. What is owed is only that the engine '
        'preserves that ordering into Dart. If it does not, a superseded show '
        'echo is believed and changes emits a spurious true — which under '
        'AD-18 is a cleared editor and a fresh clipboard read against a panel '
        'on its way out. Recorded as DW-25. '
        'Both are written up as steps in '
        'test/platform/runtime-observation-checklist.md: group C step 5 for '
        'the visible-and-focused panel, step 6 for the focus-loss hide, and '
        'step 7 for the echo ordering, each with an expected result. '
        'It owes one more claim, and this one the session procedure carries no '
        'entry for — DW-12 deliberately added none, because inserting a step '
        'renumbers every citation below it. The claim is that a close is a '
        'dismissal rather than an exit: that activating a real window '
        "manager's close control, with setPreventClose(true) in effect, "
        'delivers the close event to the plugin with the toplevel still '
        'mapped, so the adapter hide is what actually puts the panel away; '
        'that the daemon is still resident afterwards; and that the hotkey '
        'brings the same warm window back rather than building a new one. Only '
        'a window manager can produce that event, and there is none here, so '
        'what runs instead is the adapter driven from a fake close event in '
        'test/infrastructure/panel/window_manager_panel_visibility_test.dart '
        'and a source pin on the flag in '
        'test/architecture/composition_wiring_test.dart. '
        'Reconciling the window events added three more '
        'claims of the same kind, and this container can observe none of them. '
        'First, DW-33: that a window manager with focus-stealing prevention '
        'maps the panel without handing it the keyboard and the panel stays '
        'up. The adapter now answers a focus-out only when a focus-in first '
        'said the window ever held the keyboard, and only a real compositor '
        'can produce the map-without-focus that tells the two apart. Second, '
        'DW-32: that clicking away during a second summon of an '
        'already-visible panel dismisses it once that round trip ends. The '
        'blur is latched while a request of ours is outstanding and '
        'reconsidered when the request chain lets go, so what is owed is that '
        'a real click-away really does arrive in that order and really is '
        'answered afterwards. That last part is the sharp half: the release '
        'drops the blur if a focus-in arrived in between, and a focus-in our '
        'own show raised by mapping the window is indistinguishable here from '
        'the user clicking back onto the panel, so what a real session has to '
        'show is which of the two a compositor actually delivers during one of '
        'our round trips. Third, the same requirement seen from the other '
        'side: that a panel the window manager brings back on its own — '
        'deiconified after a minimize, or mapped by a show nobody here asked '
        'for — is handed the keyboard again before any focus-out reaches it. '
        'The adapter forgets the keyboard whenever '
        'the mirror goes to false and neither of those arms restores it when '
        'the panel comes back, so where a window manager brings the panel back '
        'without focusing it, that panel cannot answer a click-away until the '
        'user clicks into it first. Group C above observes a '
        'focus-loss hide from a panel that is already settled and already '
        'focused, so a completed run of it settles none of these; the same '
        'boundary is written up under "Not covered here" in '
        'test/platform/runtime-observation-checklist.md. Nothing is added to '
        'that procedure for them, for the reason DW-12 added nothing: a new '
        'entry renumbers every citation below it. '
        'DW-30 owes one more, and this one is not a mirror-accuracy question '
        'but the premise the whole attribution table rests on: that a real '
        'task-bar minimise, a workspace switch and a show-desktop gesture '
        'reach this adapter as a window-state-event carrying minimize, and '
        'that a real dismissal — the hotkey toggle, the window manager '
        'close control, a compositor unmapping the panel — reaches it as hide '
        'or as close. The event *name* is now what decides whether the text '
        'the user typed survives the panel coming back: a minimize is '
        'attributed iconified and the session survives it, while hide and '
        'close are attributed dismissed and the next summon clears the panel '
        'and re-reads the clipboard. Everything that runs here asserts that '
        'premise against FakePanelWindow, which emits whichever name a row '
        'hands it, so the mapping from gesture to event name is assumed '
        'rather than observed, and getting it wrong loses work the user typed '
        'or keeps work they asked to be rid of. Only a real window manager '
        'can produce those gestures and there is none here. Nothing is added '
        'to the procedure for it either, for the same renumbering reason.',
  );
}
